# Generated by Django 5.1.2 on 2024-12-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='basket',
        ),
    ]
