# Generated by Django 5.1.2 on 2024-12-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_user_basket'),
        ('users', '0003_remove_customuser_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='basket',
            field=models.ManyToManyField(null=True, to='shop.product'),
        ),
    ]
