# Generated by Django 5.1.2 on 2024-12-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Electronics'), (2, 'Cosmetics'), (3, 'Furniture'), (4, 'Clothing'), (5, 'Other'), (6, 'Food')], default=5),
        ),
    ]
