# Generated by Django 5.1.2 on 2024-12-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('Electronics', 'ELECTRONICS'), ('Cosmetics', 'COSMETICS'), ('Furniture', 'FURNITURE'), ('Clothing', 'CLOTHING'), ('Other', 'OTHER'), ('Food', 'FOOD')], default='OTHER'),
        ),
    ]
