# Generated by Django 5.1.2 on 2024-12-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_user_basket_product_user_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_basket',
        ),
    ]
